export const TRANSACTION_TRANSFER_REQUEST = 'TRANSACTION_TRANSFER_REQUEST';
export const TRANSACTION_TRANSFER_SUCCESS = 'TRANSACTION_TRANSFER_SUCCESS';
export const TRANSACTION_TRANSFER_FAIL = 'TRANSACTION_TRANSFER_FAIL';
export const TRANSACTION_TRANSFER_CLEAR = 'TRANSACTION_TRANSFER_CLEAR';

export const TRANSACTION_MINE_REQUEST = 'TRANSACTION_MINE_REQUEST';
export const TRANSACTION_MINE_SUCCESS = 'TRANSACTION_MINE_SUCCESS';
export const TRANSACTION_MINE_FAIL = 'TRANSACTION_MINE_FAIL';

export const TRANSACTION_DETAILS_REQUEST = 'TRANSACTION_DETAILS_REQUEST';
export const TRANSACTION_DETAILS_SUCCESS = 'TRANSACTION_DETAILS_SUCCESS';
export const TRANSACTION_DETAILS_FAIL = 'TRANSACTION_DETAILS_FAIL';
